### ISSUE TITLE
关于神奇API

### ISSUE THREAD

**Issue by Jerry-FaGe** [Genshin-bots/gsuid_core#19]
请问现在神奇API相关功能还有在维护么。我试着上了一个但是好像并没有过验证，下次请求依然1403。而且我听说 mys 改用 V4 版本了，那 `gt` 参数是不是应该改名字呢？

**Comment by KimigaiiWuyi** [comment]
有关这方面的问题可以在群里或者Q上讨论

**Comment by niuhuan** [comment]
群里 ？  有无或链接？
