### ISSUE TITLE
mys设备绑定问题

### ISSUE THREAD

**Issue by iedhgherljhfloj** [Genshin-bots/gsuid_core#56]
![屏幕截图(51)](https://github.com/Genshin-bots/gsuid_core/assets/125035359/49f30d5e-caaa-4a6d-834c-2f31a73eec44)
![屏幕截图(52)](https://github.com/Genshin-bots/gsuid_core/assets/125035359/b403c15a-0cc6-4021-9761-babb49edd340)

**Comment by iedhgherljhfloj** [comment]
绑定无响应，且过后关于米游社的指令比如【探索】【uid23456789】这样的也直接无响应了，另外【原图】也是类似

**Comment by KimigaiiWuyi** [comment]
因为填少东西了，文档忘记更新了, 试一下多加一个device_info
`mys设备登录{"fp":"38fff985f","device_id":"1234-5678-9999999-wcdd", "device_info": 'Unknown/Unknown/Unknown/Unknown'}`

**Comment by iedhgherljhfloj** [comment]
> 因为填少东西了，文档忘记更新了, 试一下多加一个device_info `mys设备登录{"fp":"38fff985f","device_id":"1234-5678-9999999-wcdd", "device_info": 'Unknown/Unknown/Unknown/Unknown'}`

device_info这个是需要我自己的参数吗，没看到有，直接复制报（绑定格式错误...）

**Comment by KimigaiiWuyi** [comment]
> > 因为填少东西了，文档忘记更新了, 试一下多加一个device_info `mys设备登录{"fp":"38fff985f","device_id":"1234-5678-9999999-wcdd", "device_info": 'Unknown/Unknown/Unknown/Unknown'}`
> 
> device_info这个是需要我自己的参数吗，没看到有，直接复制报（绑定格式错误...）

噢我写错了应该是双引号，其他用你自己的参数就可以了，device_info可以复制
`mys设备登录{"fp":"38fff985f","device_id":"1234-5678-9999999-wcdd", "device_info": "Unknown/Unknown/Unknown/Unknown"}`

**Comment by iedhgherljhfloj** [comment]
> > > 因为填少东西了，文档忘记更新了, 试一下多加一个device_info `mys设备登录{"fp":"38fff985f","device_id":"1234-5678-9999999-wcdd", "device_info": 'Unknown/Unknown/Unknown/Unknown'}`
> > 
> > 
> > device_info这个是需要我自己的参数吗，没看到有，直接复制报（绑定格式错误...）
> 
> 噢我写错了应该是双引号，其他用你自己的参数就可以了，device_info可以复制 `mys设备登录{"fp":"38fff985f","device_id":"1234-5678-9999999-wcdd", "device_info": "Unknown/Unknown/Unknown/Unknown"}`

没反应
02-28 23:03:23 [INFO] gsuid_core.handler | [Command] command=mys设备登录, text={"fp":"38d7xxxx","device_id":"0365DEC5-xxxx-432B-87A9-74xxxx8E54D", "device_info": "Unknown/Unknown/Unknown/Unknown"}
Task exception was never retrieved
future: <Task finished name='Task-10370' coro=<send_add_device_msg() done, defined at C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\sv.py:34> exception=KeyError('deviceFingerprint')>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
    result = await func(bot, event)
  File "C:\Users\Administrator\Desktop\gsuid_core\gsuid_core\plugins\core_command\user_login\__init__.py", line 126, in send_add_device_msg
    device_id, fp, data['deviceFingerprint'], user.cookie
KeyError: 'deviceFingerprint'
