### ISSUE TITLE
米遊社 API 回傳錯誤碼 5003

### ISSUE THREAD

**Issue by seriaati** [Genshin-bots/gsuid_core#57]
最近在試著搞懂米遊社的 API，因緣際會下找到了這個項目。
我試著呼叫實時便籤的 API 接口，但總是回傳給我 5003 錯誤，並且沒有任何錯誤訊息。
我翻了下 gsuid_core 的程式碼，5003 在 `_DEAD_CODE` 裡並且需要某種特殊處理的樣子…
不知道大佬有沒有處理 5003 相關的經驗，能否分享一下？

**Comment by KimigaiiWuyi** [comment]
`_DEAD_CODE`中的所有retcode代表`米游社`识别到了这是一次风险请求。
目前有两种行之有效的方式：
1. 通过调取某些平台的*"OCR"*(may)服务，通过米游社的极验请求
2. 在请求中携带正确的FP，FP的请求方式该项目以给出

**Comment by seriaati** [comment]
了解，我會試試的，非常感謝

**Comment by seriaati** [comment]
那請問要如何採集使用者的 `device_id` 跟 `fp` 呢

**Comment by seriaati** [comment]
另外，儘管我已經在 header 中設置了 `x-rpc-device_id` 以及 `x-rpc-device_fp`，仍然得到 5003 錯誤

**Comment by KimigaiiWuyi** [comment]
> 另外，儘管我已經在 header 中設置了 `x-rpc-device_id` 以及 `x-rpc-device_fp`，仍然得到 5003 錯誤 請問是否是因為缺失了 `device_info`? 並且即便使用了項目中的 [`generate_fake_fp`](https://github.com/Genshin-bots/gsuid_core/blob/f9b5e04ab5dc5f619b7d2f8ebc755991188927b4/gsuid_core/utils/api/mys/request.py#L162) 和 [`get_device_id`](https://github.com/Genshin-bots/gsuid_core/blob/f9b5e04ab5dc5f619b7d2f8ebc755991188927b4/gsuid_core/utils/api/mys/request.py#L138) ，仍然會得到 1034， `DEAD_CODE` 之一。

fakefp是没有用的，请使用正常的fp
请求流程代码中已给出
https://github.com/Genshin-bots/gsuid_core/blob/f9b5e04ab5dc5f619b7d2f8ebc755991188927b4/gsuid_core/utils/api/mys/request.py#L178

**Comment by seriaati** [comment]
但是 `generate_fake_fp` 裡不是也使用了 `generate_fp` 嗎？

**Comment by KimigaiiWuyi** [comment]
> 但是 `generate_fake_fp` 裡不是也使用了 `generate_fp` 嗎？

generate_fake_fp使用了虚假的设备信息调用了generate_fp生成了虚假的fp
你需要使用真实的安卓设备信息（常用米游社的手机），提取成功设备信息之后，调用generate_fp
可以检查[文档](https://docs.sayu-bot.com/Advance/BindDevice.html)第三节的方法
