### ISSUE TITLE
【功能建议】是否考虑新增一个

### ISSUE THREAD

**Issue by mengluo04** [Genshin-bots/gsuid_core#70]
例如插件开发教程里面的`insert_uid`和`get_uid_by_game`，开发的不是游戏插件，调用的方法第一反应是和游戏相关的。
或者说有没有办法给予base_model创建插件自己的数据库表，有的话能加在文档里面吗

**Comment by KimigaiiWuyi** [comment]
继承base_model创建表也是可以的，加上table=True即可
这个方法名称不太好改，游戏类的比较通用

**Comment by mengluo04** [comment]
> 继承base_model创建表也是可以的，加上table=True即可 这个方法名称不太好改，游戏类的比较通用

有项目的实例代码可以抄抄吗，不太熟

**Comment by KimigaiiWuyi** [comment]
> > 继承base_model创建表也是可以的，加上table=True即可 这个方法名称不太好改，游戏类的比较通用
> 
> 有项目的实例代码可以抄抄吗，不太熟

之后会在文档里补充

**Comment by mengluo04** [comment]
> > > 继承base_model创建表也是可以的，加上table=True即可 这个方法名称不太好改，游戏类的比较通用
> > 
> > 
> > 有项目的实例代码可以抄抄吗，不太熟
> 
> 之后会在文档里补充

好的

**Comment by KimigaiiWuyi** [comment]
[文档](https://docs.sayu-bot.com/CodePlugins/PluginsDataBase.html)已补充
在往下拉的`额外、继承Base_Model`章节中

**Comment by mengluo04** [comment]
> [文档](https://docs.sayu-bot.com/CodePlugins/PluginsDataBase.html)已补充 在往下拉的`额外、继承Base_Model`章节中

好的
