### ISSUE TITLE
【建议/疑问】群聊发送at消息能否选择at的位置

### ISSUE THREAD

**Issue by mengluo04** [Genshin-bots/gsuid_core#71]
现在使用bot.send(at_sender=TRue)默认是在消息最后面才at用户，能放到最前面吗，调换参数位置没用

**Comment by KimigaiiWuyi** [comment]
需要修改一下适配器, 晚点我看一眼

**Comment by KimigaiiWuyi** [comment]
应该可以了，nb2的话需要升级一下适配器`nonebot-plugin-genshinuid`的插件版本
这样就会按照core的消息列表位置去发送
![image](https://github.com/user-attachments/assets/136d74d5-a367-43c7-bbdf-fcf111ecde3e)

**Comment by mengluo04** [comment]
> 应该可以了，nb2的话需要升级一下适配器`nonebot-plugin-genshinuid`的插件版本 这样就会按照core的消息列表位置去发送 ![image](https://private-user-images.githubusercontent.com/55526518/359615485-136d74d5-a367-43c7-bbdf-fcf111ecde3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMDI2ODAsIm5iZiI6MTcyNDIwMjM4MCwicGF0aCI6Ii81NTUyNjUxOC8zNTk2MTU0ODUtMTM2ZDc0ZDUtYTM2Ny00M2M3LWJiZGYtZmNmMTExZWNkZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDAxMDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmM2NkOTM1YTlmYzBhMTE0MGZmMjNlOGE5NGYzZjllMmU2MTZiZWRlZmJlM2IyM2I0NTkxMGYwYmVmZGRlZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WnAq2TL0WUz042r5wCwG64gNPzOKVMk4QjKrSRzykOc)

好咧

**Comment by mengluo04** [comment]
> 应该可以了，nb2的话需要升级一下适配器`nonebot-plugin-genshinuid`的插件版本 这样就会按照core的消息列表位置去发送 ![image](https://private-user-images.githubusercontent.com/55526518/359615485-136d74d5-a367-43c7-bbdf-fcf111ecde3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjYzNjIsIm5iZiI6MTcyNDIyNjA2MiwicGF0aCI6Ii81NTUyNjUxOC8zNTk2MTU0ODUtMTM2ZDc0ZDUtYTM2Ny00M2M3LWJiZGYtZmNmMTExZWNkZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA3NDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NTliMjRiYjQ1ZTBiNDNmODZjZDcwNjA2ZDg2NmUxNTM5MmZhZmY3MDkwYTlmY2Q1YjFlZTEwMTk4NDA2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KLZj35GXoa4uq3t3C2_E5d0C6LTy3Fl1ztuf2e9CSk0)

genshinuid里面的推送，at位置错位了，影响到了
![image](https://github.com/user-attachments/assets/3d36bab7-fdad-454c-800c-1ac40f7ab99a)

**Comment by KimigaiiWuyi** [comment]
这个应该是预期效果吧
at某人 + 提醒

**Comment by mengluo04** [comment]
> 这个应该是预期效果吧 at某人 + 提醒

我最开始想的是放在最前面，感觉放最前面是最常见的，虽然现在也不影响功能就是了
