### ISSUE TITLE
poetry install安装依赖报错

### ISSUE THREAD

**Issue by MoonStarrySky** [Genshin-bots/gsuid_core#82]
![image](https://github.com/user-attachments/assets/688be0b1-6922-4f8e-9e1c-e70da0666ef1)

**Comment by KimigaiiWuyi** [comment]
网络问题,无法访问`https://mirrors.bfsu.edu.cn/`, 你可以尝试修改pypi的源

**Comment by MoonStarrySky** [comment]
> 网络问题,无法访问`https://mirrors.bfsu.edu.cn/`, 你可以尝试修改pypi的源

好的

**Comment by devil233-ui** [comment]
> 网络问题,无法访问`https://mirrors.bfsu.edu.cn/`, 你可以尝试修改pypi的源

这个看着不像网络问题，而是不支持pep517？
![c8b675aad975b6558f484f6fb5e486d0](https://github.com/user-attachments/assets/3b39c8e0-4e8a-408a-a3f0-2beebbf5da74)
查网上方案尝试用预编译的装也不行
![34697a24ef0067bf7823f2ee63916e05](https://github.com/user-attachments/assets/75a1408e-694e-4154-a737-64cf1eaad0ac)
![e795e22cc3a40cb53a78060aa49be96c](https://github.com/user-attachments/assets/d0aff9a4-aa8d-492e-be00-4c28a5858230)

换pdm装则报错如下
[pdm-install-ygwd3jyl.log](https://github.com/user-attachments/files/18166846/pdm-install-ygwd3jyl.log)

**Comment by KimigaiiWuyi** [comment]
你可以自己安装一下更高版本的pillow试一下
`poetry run pip install pillow -U`

**Comment by devil233-ui** [comment]
> 你可以自己安装一下更高版本的pillow试一下 `poetry run pip install pillow -U`

可是我上面第二张图装的就是高版本来着。

用您的方法尝试后也是一样的报错
![image](https://github.com/user-attachments/assets/e348752d-7c82-453b-bca1-87ab1101a80f)
