### ISSUE TITLE
与bot连接后没有反应

### ISSUE THREAD

**Issue by NdR60A** [Genshin-bots/gsuid_core#86]
使用的是Nonebot2中的Telegram适配器，成功连接后，给bot发送信息无反应，看看怎么个事，谢谢
![image](https://github.com/user-attachments/assets/2d061121-414e-4e22-b48c-8058bcc96e1a)

**Comment by KimigaiiWuyi** [comment]
注意消息中的`user_pm`为6，代表你是普通用户权限， 无法执行高级权限命令`core安装插件`
请将目录中的`config.json`的`master`值，修改为你的`user_id`，类型为`List[str]`
文档也有示例~

**Comment by NdR60A** [comment]
抱歉，再次打扰，我在 config.json 中修改了连接的地址，那么在 NoneBot2 文件夹中，修改哪里对应的连接呢，现在连接不上了

> 注意消息中的`user_pm`为6，代表你是普通用户权限， 无法执行高级权限命令`core安装插件` 请将目录中的`config.json`的`master`值，修改为你的`user_id`，类型为`List[str]` 文档也有示例~

**Comment by KimigaiiWuyi** [comment]
> 抱歉，再次打扰，我在 config.json 中修改了连接的地址，那么在 NoneBot2 文件夹中，修改哪里对应的连接呢，现在连接不上了
> 
> > 注意消息中的`user_pm`为6，代表你是普通用户权限， 无法执行高级权限命令`core安装插件` 请将目录中的`config.json`的`master`值，修改为你的`user_id`，类型为`List[str]` 文档也有示例~

``python

if hasattr(driver.config, 'gsuid_core_botid'):
    BOT_ID = str(uuid.uuid4())[:10]
else:
    BOT_ID = 'NoneBot2'

if hasattr(driver.config, 'gsuid_core_host'):
    HOST = driver.config.gsuid_core_host
else:
    HOST = 'localhost'

if hasattr(driver.config, 'gsuid_core_port'):
    PORT = driver.config.gsuid_core_port
else:
    PORT = '8765'
```

NoneBot2中可尝试在`.env`中创建`gsuid_core_host=xxxx`, `gsuid_core_port=8765`
类似这样的环境变量来解决

**Comment by NdR60A** [comment]
> > 抱歉，再次打扰，我在 config.json 中修改了连接的地址，那么在 NoneBot2 文件夹中，修改哪里对应的连接呢，现在连接不上了
> > > 注意消息中的`user_pm`为6，代表你是普通用户权限， 无法执行高级权限命令`core安装插件` 请将目录中的`config.json`的`master`值，修改为你的`user_id`，类型为`List[str]` 文档也有示例~
> 
> ```python
> if hasattr(driver.config, 'gsuid_core_botid'):
>     BOT_ID = str(uuid.uuid4())[:10]
> else:
>     BOT_ID = 'NoneBot2'
> 
> if hasattr(driver.config, 'gsuid_core_host'):
>     HOST = driver.config.gsuid_core_host
> else:
>     HOST = 'localhost'
> 
> if hasattr(driver.config, 'gsuid_core_port'):
>     PORT = driver.config.gsuid_core_port
> else:
>     PORT = '8765'
> ```
> 
> NoneBot2中可尝试在`.env`中创建`gsuid_core_host=xxxx`, `gsuid_core_port=8765` 类似这样的环境变量来解决

非常感谢，已经成功连接啦
