### ISSUE TITLE
poetry install报错

### ISSUE THREAD

**Issue by jiang068** [Genshin-bots/gsuid_core#88]
安装gscore的时候，在gsuid_core目录下poetry install报错，Ubuntu22.04
ubuntu@VM01-vm01:~/Desktop/gsuid_core$ poetry install

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [source.0] Additional properties are not allowed ('priority' was unexpected)
  

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│ 
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│ 
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
并且在多个模拟机上有的也是这样，复现概率高，在同一个模拟机上多试几次有时又能依赖安装成功，有时候又不行

**Comment by KimigaiiWuyi** [comment]
请检查poetry版本，过低需要更新
我的poetry版本
```shell
Name: poetry
Version: 1.8.3
Summary: Python dependency management and packaging made easy.
Home-page: https://python-poetry.org/
Author: Sébastien Eustace
Author-email: sebastien@eustace.io
License: MIT
Location: C:\Users\Wuyi\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: build, cachecontrol, cleo, crashtest, dulwich, fastjsonschema, installer, keyring, packaging, pexpect, pkginfo, platformdirs, poetry-core, poetry-plugin-export, pyproject-hooks, requests, requests-toolbelt, shellingham, tomlkit, trove-classifiers, virtualenv
Required-by: poetry-plugin-export
```
